### ISSUE TITLE
should the twitterLink at the end of the readme just be link?

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/angular-bind-to-controller-readme#3]
![image](https://cloud.githubusercontent.com/assets/15042882/14718477/ea82d6e4-07c4-11e6-8123-387b5e989710.png)
i may be misunderstanding this, but the 'link' value seems to be coming out of nowhere at the end of the readme, i'd imagine that within the controller it needs to be set to this.link = 'https://twitter.com'  for that to work.

**Comment by pletcher** [comment]
Yep! Related to #2, which fixed it.
